### ISSUE TITLE
Limiters for the Y coordinate

### ISSUE THREAD

**Issue by ghost** [robbykraft/Panorama#23]
Hi Robby,

Thanks for this great resource, is making my life easier :)
I have one question:how to make limiters for coordinate Y, so I could not look above or below a certain azimuth?

Thanks,
Grigory

**Comment by robbykraft** [comment]
Hi Grigory, sorry for such a late response,
If it's still helpful, you want to make a new `-(GLKMatrix4) getDeviceOrientationMatrix` so that your custom matrix comes in on this line:
```
_attitudeMatrix = GLKMatrix4Multiply([self getDeviceOrientationMatrix], _offsetMatrix);
```
there is in-progress code for "prevent head tilt" at line 380 which chops up the orientation matrix and limits it in the Y direction much like you are speaking about.
this should get you most of the way there
