### ISSUE TITLE
GLKTextureLoader: EXC_BAD_ACCESS

### ISSUE THREAD

**Issue by Rommanski** [robbykraft/Panorama#55]
Hello @robbykraft  Thank you for this great project!
I have builded application for swift and all works well. App works when I load image from project:

`panoramaView.setImageWithName("2048.jpg")`

But, when I try to show image from photo library, I got error EXC_BAD_ACCESS. Error happens in method:

`-(GLKTextureInfo *) loadTextureFromImage:(UIImage *) image`

Line:

`info = [GLKTextureLoader textureWithCGImage:image.CGImage options:options error:&error];`

I'm picking image from photo library with UIImagePickerController. Image loads and shows fine.
Will be glad for any help!

**Comment by kopiro** [comment]
up!

**Comment by Rommanski** [comment]
Hello @kopiro, do you have same problem as my?

**Comment by kopiro** [comment]
yes :(
Do you have any idea?

It works fine, but I'm trying to wrap in a Titanium module and it crashes.

**Comment by Rommanski** [comment]
@kopiro Don't have any ideas. I will let you know when find solution. Good to know that I'm not alon

**Comment by Rommanski** [comment]
Hello @kopiro I have fixed the problem. This error occurred due to unsupportable image size (image must have proportion 2x1). I have created crop tool for resizing any image. You can find tool here:

https://gist.github.com/Rommanski/142f0b56ef553222a8fc221e2d4deee6

**Comment by kopiro** [comment]
My image is 2x1 :(

**Comment by kopiro** [comment]
Should I crop it anyway?

**Comment by Rommanski** [comment]
@robbykraft Maybe, there is reason to include same tool to the library? This solution will prevent problems with incorrect image size.

**Comment by Rommanski** [comment]
@kopiro Of corse not. Unfortunately, I don't have experience with Titanium. Do you try to include this native module to your app?

**Comment by kopiro** [comment]
I'm working to wrap it in a Titanium module, but it doesn't works with this crash.
Trying to crop anyway, maybe it helps.

**Comment by robbykraft** [comment]
thanks for solving @Rommanski

yes, the instruction is in the readme, though after hearing from you, maybe it's not obvious enough.

i agree! including a scaling library would be helpful, though, i'm hung up on user design details - 
1) what happens when image is not 1:2? do we preserve aspect + crop, or scale axes independently?

I'm testing to see what I can do, a 1:2 but not a power of 2 (500x250) - I'm getting no errors generated, and "info" appears to load, (even though it doesn't show, as it shouldn't): 

`info = [GLKTextureLoader textureWithCGImage:image.CGImage options:options error:&error];`

a work around would be load the image twice. First time as a UIImage, validate width and height properties, then if all checks out load the image again as a GLKTexture..  there must be a more elegant solution

**Comment by kopiro** [comment]
Is there any chances that you can help me? I didn't solved yet :(
Thanks in advance

**Comment by robbykraft** [comment]
@kopiro are you using the included image? what are the dimensions of the image you are using?

**Comment by kopiro** [comment]
I have answered on the other issue, thank you :)
