### ISSUE TITLE
setImage and setImageWithName not working when I try to set it from directory or bundle directory

### ISSUE THREAD

**Issue by Harinderjit** [robbykraft/Panorama#68]
I am trying to set image with name or set image by fetching the image from directly but both not working please let me know if somebody got same issue

**Comment by robbykraft** [comment]
It might be an issue with including the file in the bundle, which is Project Settings -> Build Phases -> Copy Bundle Resources tab.

otherwise, I would try this type of line to make sure the file is there: this line is in the swapTexture function `[[NSFileManager defaultManager] fileExistsAtPath:textureFile]`

**Comment by Harinderjit** [comment]
Thanks for your reply but I found it was my mistake actually I was not setting the image sizes as mentioned by you.
